### ISSUE TITLE
Importing an already imported file produces a result that seems to be wrong

### ISSUE THREAD

**Issue by lukyth** [ThisIsManta/vscode-code-quicken#1]
## Steps to reproduce
1. There's already an import statement.
```js
import * as Channel from '../tw-channels/Channel'
```
2. Use `code-quicken` command `Insert an import/require statement`
3. Select `Channel`. (It's the file located at `../tw-channels/Channel`)
4. Select `isGeneralChannel`. (The function is named export)
5. Re-do step 2-3 again.
6. Select `isDirectChannel`. (The function is named export)
7. The result was the code below.
```js
import  { isDirectChannel } from '../tw-channels/Channel'
// ...
import * as Channel, { isGeneralChannel } from '../tw-channels/Channel'
```
## Expected behavior
1. It should import nothing new since `import * as Channel` already import every named exports on that module.
2. It could suggest a user that they don't have to import the function and call it by `Channel.isDirectChannel`.
3. If you think having a named import with a wildcard import is fine, at least it should produce a result like the code below.
```js
import * as Channel, { isDirectChannel, isGeneralChannel } from '../tw-channels/Channel'
```

**Comment by ThisIsManta** [comment]
Fixed! Thanks for helping **Code Quicken** a better extension.
